[package]
name = "passepartout"
version = "0.1.3"
edition = "2021"
description = "Library for pass"
authors = ["Karl Felix Schewe"]
readme = "README.md"
license = "GPL-3.0-only"
repository = "https://github.com/kardwen/passepartout"
keywords = ["pass"]
categories = ["authentication"]

[dependencies]
arboard = { version = "3.4.1", features = ["wayland-data-control"] }
dirs = "5.0.1"
# futures = "0.3"
icu = "1.5.0"
thiserror = "2.0.4"

[profile.dev]
opt-level = 0
debug = 2

[profile.release]
lto = true
opt-level = 3
debug = 1
strip = false
panic = "abort"
codegen-units = 1
